### ISSUE TITLE
Bug: calculation of request time sum

### ISSUE THREAD

**Issue by Kolobok12309** [artmizu/nuxt-prometheus#11]
Found invalid calculation of total requests time in your `calculateTime`

https://github.com/artmizu/nuxt-prometheus/blob/7073d48f627fa084ed7a9053495764b14859cdcc/src/runtime/utils.ts#L3

Ruined test cases are the second and last. 

<details>
<summary>Test cases</summary>

```js
{
      input: [
        { start: 1, end: 10 },
        { start: 5, end: 7 },
        { start: 15, end: 30 },
      ],
      res: 24,
    },
    {
      input: [
        { start: 100, end: 101 },
        { start: 100, end: 105 },
        { start: 95, end: 102 },
      ],
      // 5 from function
      res: 10,
    },
    {
      input: [
        { start: 53, end: 55 },
        { start: 58, end: 78 },
        { start: 90, end: 95 },
      ],
      res: 27,
    },
    {
      input: [
        { start: 45, end: 75 },
        { start: 65, end: 75 },
        { start: 85, end: 90 },
      ],
      res: 35,
    },
    {
      input: [
        { start: 50, end: 75 },
        { start: 35, end: 55 },
        { start: 10, end: 15 },
        { start: 55, end: 60 },
      ],
      // 25 from function
      res: 45,
    },
```
</details>

In the last test not sorted input, it possible if `Object.values` return different ordered array in different js realizations

**Comment by artmizu** [comment]
@Kolobok12309 

my apologies for the late response, current **calculateTime** function is require times in the **input** property to be sorted as you mention, according to this you input data is invalid. for now i don't see any reason to support this kind of the input

so for now i'll close the issue, but thank you for the feedback
