### ISSUE TITLE
 ERROR  Cannot start nuxt:  File URL path must be absolute

### ISSUE THREAD

**Issue by HollyCreep** [artmizu/nuxt-prometheus#22]
I couldn't get it to work. I tried on Node 16xx and 18xx, none of them worked, generating the same error after installing nuxt-prometheus module.

Node version: 16.20.2 | 18.14.2
Nuxt version: 3.1.0

![image](https://github.com/artmizu/nuxt-prometheus/assets/49692932/04e4068a-ec10-42bf-b645-1a93064c3e28)

**Comment by artmizu** [comment]
@HollyCreep 

if you're trying to use latest version of the package, probably it's incompatible with the nuxt version 3.1.0. because last version of the package is using nuxt 3.6.5 under the hood

could you try to use earlier version of the package, for example 2.1.0?

**Comment by HollyCreep** [comment]
@artmizu Thanks for your quickly reply!

I tried a new Nuxt project, but that didn't succeed either. Could you provide an working example ?

What you mean  with  `package  2.1.0` ? Are you suggesting I should use Nuxt 2? Or are you referring to your  own module? The versions I found of your module were `0.0.0` `0.1.0` `0.1.1`.


![image](https://github.com/artmizu/nuxt-prometheus/assets/49692932/d2efae82-0b81-4767-94d9-2c350bc1cc7f)
![image](https://github.com/artmizu/nuxt-prometheus/assets/49692932/8467aa3c-17b8-4c91-b20b-d6b6f1de685f)


Thank you again for your help!
