### ISSUE TITLE
feature request: allow Nuxt Bridge

### ISSUE THREAD

**Issue by AndreyYolkin** [artmizu/nuxt-prometheus#27]
Can you please add nuxt 2.16+ with bridge enabled into module constraints? When Nitro enabled, current version is working as expected, unlike  @artmizu/analytics-nuxt-2

**Comment by artmizu** [comment]
@AndreyYolkin https://github.com/artmizu/nuxt-prometheus/releases/tag/v2.2.0

thank you for the participation :)
