### ISSUE TITLE
Some questions from newbies

### ISSUE THREAD

**Issue by e112121** [artmizu/nuxt-prometheus#31]
This is my first time using prometheus, I think it's cool and useful，but i have some question.

first http://26.26.26.1:3000 is my local url

when i open http://26.26.26.1:3000/metrics,the web page look like this

![image](https://github.com/artmizu/nuxt-prometheus/assets/69035266/554b87db-2c8d-4180-822c-d631798dba86)

and web page look like this when I open http://26.26.26.1:3000/health

![image](https://github.com/artmizu/nuxt-prometheus/assets/69035266/add7b66c-1b77-4a6d-b5c6-a906d980333b)

but,i wanna web page like the image of README 

![image](https://github.com/artmizu/nuxt-prometheus/assets/69035266/84118ee0-d65d-45c2-a200-6ffc97aa3321)

what should I do

**Comment by artmizu** [comment]
> This is my first time using prometheus, I think it's cool and useful，but i have some question.
> 
> first http://26.26.26.1:3000 is my local url
> 
> when i open http://26.26.26.1:3000/metrics,the web page look like this
> 
> ![image](https://private-user-images.githubusercontent.com/69035266/287693316-554b87db-2c8d-4180-822c-d631798dba86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTE5OTEsIm5iZiI6MTcwMTc1MTY5MSwicGF0aCI6Ii82OTAzNTI2Ni8yODc2OTMzMTYtNTU0Yjg3ZGItMmM4ZC00MTgwLTgyMmMtZDYzMTc5OGRiYTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiYzQ4OWFjMjQyNjkwNjRmN2ZhNmY5ZTczMWFlMjA2MjI0MzZkYTgyZGU3NmNmNzk5Y2YzZDU2NDg4ODEyZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7CBEvvticIn9wFXFhx6wNlL-Rhz0CcEd4AmVC0Nsfjc)
> 
> and web page look like this when I open http://26.26.26.1:3000/health
> 
> ![image](https://private-user-images.githubusercontent.com/69035266/287693772-add7b66c-1b77-4a6d-b5c6-a906d980333b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTE5OTEsIm5iZiI6MTcwMTc1MTY5MSwicGF0aCI6Ii82OTAzNTI2Ni8yODc2OTM3NzItYWRkN2I2NmMtMWI3Ny00YTZkLWI1YzYtYTkwNmQ5ODAzMzNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MTQ5NDc4NGYxY2I0ODg2Y2FkZjlmMWU0MzI5YTUwZmFhNDU3NTZkMWE0MzliZTM5ODhiYmExZTFmZGExZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bj301twol6XVCGcrYhlc5TM3NaI0LoTCWqTF1AW5BG8)
> 
> but,i wanna web page like the image of README
> 
> ![image](https://private-user-images.githubusercontent.com/69035266/287694076-84118ee0-d65d-45c2-a200-6ffc97aa3321.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTE5OTEsIm5iZiI6MTcwMTc1MTY5MSwicGF0aCI6Ii82OTAzNTI2Ni8yODc2OTQwNzYtODQxMThlZTAtZDY1ZC00NWMyLWEyMDAtNmZmYzk3YWEzMzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZGY2ZDY4ZDgxNTk1YTAzNTM2ZjJhNmQxMjRlNzgyOGM3M2I5ODZkNjJhYWUyMjYxNWExMzJlMTVmZWRlN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3HzZMLZpRgr-Igvkmt_LfpHRhy0-JPqt3txablMv0lc)
> 
> what should I do

hello 
you can't see the page like on your last screenshot on the nuxt side. This module is just export metrics, but Prometheus on the other side need to accept it, also you need Grafana to visualize the metrics. 

Please check the other articles in internet about Grafana and Prometheus
