### ISSUE TITLE
Uninstall Problem

### ISSUE THREAD

**Issue by andamansunda** [artmizu/nuxt-prometheus#44]
I installed the module, then I realized that we did not need it. I then uninstalled the package. So now when I run 'npm run dev', I then get this message popping up several times every 15 seconds or so ' WARN  [Vue Router warn]: No match found for location with path "/metrics". I have deleted the .nuxt folder, the pnpm-lock file, and the node_modules folder. I have removed the reference in the modules list in nuxt.config file. Then I ran pnpm install and npm run dev. And I still get this warning message.

**Comment by artmizu** [comment]
@andamansunda 
Hi, thank you for the report
module doesn't produce any system-wide side effects, so route '/metrics' is created through Nuxt API: 
<img width="483" alt="image" src="https://github.com/artmizu/nuxt-prometheus/assets/12496464/e5b7bd23-7ee9-4948-a658-44e118084ab6">

Maybe some browser tabs with /metrics URL are still active or in .nuxt-config you still have a route with this URL, it doesn't look like a module problem.

If you need a future investigation, please send a way to reproduce the problem

**Comment by andamansunda** [comment]
You are right. I did some tests, and under normal circumstances, the module can be cleanly removed. But in my case, something went wrong, and would you have any guidance on what to do to resolve this? 
 WARN  [Vue Router warn]: No match found for location with path "/metrics"
This message comes up 5 times every 15 seconds or so. I have deleted the .nuxt folder, the pnpm-lock.yaml file, and the node_modules folder then did 'pnpm install' and 'pnpm run dev', and the warning still keeps coming. Any ideas?

**Comment by artmizu** [comment]
@andamansunda 

even if the dependency exists in a project, if you don't include the package in the nuxt.config.ts it shouldn't be enabled. So if in the nuxt.config.ts you don't have it in, also the project was rebuilt everything should work fine

I don't know much about your environment, the project setup, etc. Maybe you have some tricks around build time, cache strategies for the application and modules, specific package manager setup or so
