### ISSUE TITLE
How to serve on a different port?

### ISSUE THREAD

**Issue by ennc0d3** [artmizu/nuxt-prometheus#50]
Sorry, I am not quite familiar with nuxt, wondering if it is possible to configure metrics endpoint to run on a different port ? 
Thanks

**Comment by or2e** [comment]
hi, it is possible, but you will need to write your nitro-preset and add `metricApp` to it as a separate `h3` app



You can use the [original nodejs preset](https://github.com/nitrojs/nitro/tree/v2/src/presets/node) as a basis.

<details>
  <summary>metricApp ex.</summary>
  
```ts
import { createApp, send, sendError, eventHandler } from 'h3';
import { AggregatorRegistry } from 'prom-client';

const aggregatorRegistry = new AggregatorRegistry();

const metricsApp = createApp({
    onError: (err, event) => sendError(event, err),
}).use(
    '/metrics',
    eventHandler(async (event) =>
        send(
            event,
            await aggregatorRegistry.clusterMetrics(), // In my example, I'm using nodejs clustering, so keep that in mind.
            aggregatorRegistry.contentType,
        ),
    ),
);

export default metricsApp;
```
</details>

In `nuxt.config` specify it:
```
...
  nitro: {
    preset: './nitro-presets/node-with-metric-app',
}...
```
