### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by pi0** [artmizu/nuxt-prometheus#6]
Thanks for cool module I was always thinking of exporting metrics for promotheus! 

A quick review I found some issues:

- `configKey` seems is wrong `analytics` while should probably be `promotheus` in module definition and for runtime config (https://github.com/artmizu/nuxt-prometheus/blob/aac4b81ebb581eb0e4d0b4b4dfcda970d7d1eab6/src/module.ts#L15)
- Exposed routes (/metrics, /health) can potentially conflict with user provided routes. Specially metrics. It would be nice to prefix them probably with `/_promotheus` (or at least `_`) by default and provide options to customize or disable each
- Avoid restructuring `event` object - it currently uses a deprecated method without node. prefix . And directly return response (https://github.com/artmizu/nuxt-prometheus/blob/aac4b81ebb581eb0e4d0b4b4dfcda970d7d1eab6/src/runtime/handler.ts#L7)
- Perf: We could probably directly render promethus metrics response and reduce bundle size in https://github.com/artmizu/nuxt-prometheus/blob/main/src/runtime/registry.ts.

**Comment by artmizu** [comment]
@pi0 thanks for your feedback, i really appeciate it.

I have published a new version of the package with the features you requested: https://github.com/artmizu/nuxt-prometheus/pull/7

Except for the last point from your request, could you point me in the right direction? I thought over, but couldn't understand your proposal.

**Comment by artmizu** [comment]
a quick note about the default route path: it is configured by default to be compatible with the standard prometheus configuration and quite a few tools that request a healthcheck route.

So I've just gave the possibility to customise the route paths.

**Comment by pi0** [comment]
Thanks for the updates. Regarding last one, moved to a new issue https://github.com/artmizu/nuxt-prometheus/issues/9. Cheers!
