### ISSUE TITLE
possibiliy to reduce bundle size by 40kb

### ISSUE THREAD

**Issue by pi0** [artmizu/nuxt-prometheus#9]
`prom-client` has around 40kb overhead (https://bundlephobia.com/package/prom-client@14.1.1), while it is perfectly fine for any Node.js deployment, worker builds especially can enjoy the bundle saving.

Since Prometheus format is super simple, we might replace it with an inline util that renders expected format for exported metrics.

**Comment by artmizu** [comment]
@pi0 thanks for the request

but the purpose of prom-client in this module is not only about creating an export file with rendering time metrics and API requests. It's also to create a complete solution for a wide set of standard NodeJS metrics: about memory consumption, CPU and other common things.

So users can integrate this module into their projects and not have to worry about integrating additional modules

**Comment by pi0** [comment]
I see good point! Indeed as mentioned it is mostly useful optimization for Nodeless targets. It seems harder than i thought this way. Moved issue to https://github.com/unjs/unenv/issues/70 to not forget. If we find a way for unenv mock, it will seamlessly be added for Nuxt projects and your module. Cheers.
